### PR TITLE
Updated Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by NathanBnm** [comment]
You have to move from `nl_NL` to simply `nl`.

**Comment by Vistaus** [comment]
> You have to move from `nl_NL` to simply `nl`.

Why? There's a clear distinction between nl_NL and nl_BE.

**Comment by NathanBnm** [comment]
The original language file should always have the original language code.
For example French is from France so it should be `fr` but Canadian French should be precised using `fr_CA`. You don't have to precise the country if it's the original language.

**Comment by Vistaus** [comment]
A lot of other projects do make that distinction, but oh well, I'll change it then.

**Comment by NathanBnm** [comment]
Thanks :smile: By my side I never seen this in other elementary apps.

**Pull request closed without merging**
