### PR TITLE
Update LINGUAS

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by NathanBnm** [comment]
@albanobattistella Italian translation are not available for now. Why would you update this file?
Feel free to translate it if you want, but you have to add it both in `po/LINGUAS` and `po/extra/LINGUAS`.

Then you can generate the appropriate `po` files by running the following commands in the `build` directory:
- ninja com.github.calo001.fondo-update-po
- ninja extra-update-po

The `extra` folder is meant for metadata translations (app info and changelog).

**Comment by albanobattistella** [comment]
Hi,

translated.

Regards,
Albano

**Comment by NathanBnm** [comment]
@albanobattistella you have to add `it` to the two `LINGUAS` files. Not only the one in the `extra` folder.

**Comment by calo001** [comment]
Thanks !!

**Comment by albanobattistella** [comment]
> Thanks !!

thanks to you! nice project!

**Pull request merged**
