### PR TITLE
Multi Wallpaper Slideshow capability

### PR DESCRIPTION
**Pull request by vfrico**
I open this pull request at this moment to show the ongoing work up to this date related to issue #111 

Right now is completely functional, altough it is still a lot of work to do in the design side and usability (disable / show buttons where they are not needed, etc). But the main functionality of putting a background slideshow is working (or at least it work for me).

To build the app, just execute this command:
```
./app run
```

I am open to comments about the implementation: if I have chosen the correct path of classes, names, etc...

### CODE REVIEW

**Comment by calo001** [comment]
@vfrico Hi!! First of all, thank you for help me to make Fondo a better app! I find a little busy these days, but I'll definitely be aware of the progress of your appreciable contribution! I'm really excited about this because is a great feature for Fondo!

I have some ideas that I think would be awesome:
* Have the option to add the photo to slideshow always enabled by default in all cards. (When more features come in the future, we can play with buttons visibility, but for the moment I think is better to show directly the option to the user)
* In the popup multiple show the selected photos.

What do you think?

Thank you! :)

**Comment by vfrico** [comment]
I think that having a preview of the selected photos in the popup is a great idea, although I don't know how many time it will take to implement. The first one seems a bit easier.

Also, I still haven't added a wallpaper slideshow to the history tab. This requires a lot of work to do for me, although I will try to do something interesting.

And it would be great if this repository joins to the Hacktoberfest event. You will simply need to add `hacktoberfest` tag to the repo. More info about it [here](https://hacktoberfest.digitalocean.com/details#maintainers).

**Comment by vfrico** [comment]
Right now I have a fully working example. Some work might still be needed, but this version has all the personal requirements I imposed myself to implement plus some others @calo001 proposed

The user can add and remove wallpapers from any view to the wallpaper slideshow, and can preview all the backgrounds that will be used in the slideshow.

imagen

I'd like comments about what work is missing to release the feature

**Comment by calo001** [comment]
@vfrico Hi! I'm testing the feature and works amazing! give me a chance to review some minimal details in UI, but I really loved your job!

**Comment by vfrico** [comment]
Ok, take your time to check them, but please, keep me updated!

The UX/UI part is not the best, I think

**Comment by calo001** [comment]
@vfrico Hi! just for telling you some details in the UI that I made recently!

- Replace some icons
- Use a global (slideshow selected pictures) progress bar
- Popover redesigned

Pending:
- Add to history selected pictures
- Make strings translatable

https://imgur.com/a/0ebw95B

I'm not sure if the best way, but I'll send you a pull request, for your review! :) thanks my friend!

**Comment by vfrico** [comment]
I love the new improvements done by you! 

I only made one little correction. When using horizontal wallpapers, the progress bar keeps aligned to left with an empty space on the right

imagen

Setting this property to true get this space fixed

imagen

And for the other two missing items, I'll try to upload a commit with the fixes.

**Comment by calo001** [comment]
@vfrico hey thanks! awesome! your correction looks great! 

Now just have implemented the history record for each wallapaper (in the future I wish show them as a group, but for now it's ok!), but I'm thinking in a final scenario when the user set the slideshow in elementary OS, because greeter takes the "current" wallpaper and I never have tested a xml in greeter :O

**Comment by vfrico** [comment]
Ok, perfect! I've added translations for messages on the UI.

And for Elementary OS' greeter: I don't understand what is the issue. The background used for greeter is the same than the used in the desktop background, right?

**Comment by calo001** [comment]
@vfrico Hi!, I just make a test using the XML resource in greeter but it doesn't work, greeter needs the current wallpaper (an image file) in the directory /var/lib/lightdm-data/youruser/wallpaper, but the slideshow is an XML file.

I don't know a way to change that file every lapse of time on background 😥️, so I'm thinking about some options:
- use as default the first image in the slideshow
- Allow to user select the wallpaper to use in the greeter listed in the slideshow

**Comment by vfrico** [comment]
>     * use as default the first image in the slideshow
> 
>     * Allow to user select the wallpaper to use in the greeter listed in the slideshow

I think the first one has more sense, because the implementation of the second forces to show different interface for an user in Gnome/GDM or another user in Pantheon/LightDM. I know it is a limitation, but I don't find an easier way to circunvent this.

**Comment by calo001** [comment]
@vfrico Hi! I will merge this branch and I hope to release a version in the week :) btw in my time zone, it is still October 31, I hope this can still be registered as your contribution to the hacktoberfest :smile: 
Thanks!

**Pull request merged**
