### PR TITLE
Update de_DE.po

### PR DESCRIPTION
**Pull request by Etamuk**
Updated to the latest version 1.3.7

### CODE REVIEW

**Comment by NathanBnm** [comment]
`de_DE` is not a correct language code. It should only be `de`.

**Comment by Etamuk** [comment]
> `de_DE` is not a correct language code. It should only be `de`.

Ok, in other projects there is no problem with it. So I changed de_DE to de

**Comment by NathanBnm** [comment]
Thanks. I explained why here in https://github.com/calo001/fondo/pull/70#issuecomment-575996921

**Comment by Etamuk** [comment]
No problem :-) Everything is fine. 
de_DE or de doesn't really matter for german speakers

At the end I hope Fondo will finally shown with german UI.

**Comment by NathanBnm** [comment]
I didn't think about that but for sure using `de` instead of `de_DE` is better for the OS to display the appropriate language.

With the `de` language code Fondo will show in German for sure if your OS is in German.

**Comment by Etamuk** [comment]
Yes, my OS is in German. 
At the moment Fondo is shown in english. 
But I will wait for the next update. 
Thanks

**Comment by NathanBnm** [comment]
You have conflicts on your PR. Maybe you have to check, otherwise it might not be merged.

**Comment by Etamuk** [comment]
> You have conflicts on your PR. Maybe you have to check, otherwise it might not be merged.

Thank you for remembering me.
Done.

**Pull request merged**
