### PR TITLE
Fix languages codes and split translation files

### PR DESCRIPTION
**Pull request by NathanBnm**
This PR fixes wrong translation codes and improves the way translations files are set in your app. Now the metadata translations are separated from the main translations.

Let me know if you have any questions.

**This PR is ready for review**

### CODE REVIEW

**Comment by calo001** [comment]
@NathanBnm I never thought in a separate configuration, it's an awesome structure, thanks. I'm testing adding some changes in com.github.calo001.fondo.appdata.xml, and then trying to update pot files with 
* ninja com.github.calo001.fondo-pot
* ninja com.github.calo001.fondo-update-po

But the extra folder pot files aren't getting any update :confused:

**Comment by NathanBnm** [comment]
@calo001 it's because to update the extra translations you have to execute `ninja extra-update-po`

Please merge this directly. I fixed the wrong languages codes and already re-generated the appropriate files :smile:

**Comment by calo001** [comment]
@NathanBnm Oh thanks, ok right now I do the merge :)

**Comment by NathanBnm** [comment]
Thanks! Now you can update the `appdata.xml` file if you want :smile:

**Pull request merged**
